/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lt.petuska.kpm.publish

import io.kotest.core.spec.style.WordSpec
import io.kotest.core.spec.style.scopes.WordSpecTerminalScope
import io.kotest.matchers.string.shouldContainIgnoringCase
import io.kotest.matchers.string.shouldNotContainIgnoringCase
import lt.petuska.kpm.publish.util.buildGradleFile
import lt.petuska.kpm.publish.util.gradleExec
import org.gradle.testkit.runner.BuildResult
import java.io.File

private suspend fun WordSpecTerminalScope.taskCreationTest(
  kotlinPlugin: String,
  jsTargets: List<String> = listOf(),
  jvmTargets: List<String> = listOf(),
  expectedMissingTasks: List<String> = listOf()
) {
  val jsPlugin = kotlinPlugin.equals("js", true)
  fun execute(): BuildResult {
    val jsBlock = jsTargets.joinToString(";") { "${if (!jsPlugin) "js(\"$it\")" else "target"} {browser()}" }
    val jvmBlock = if (jsPlugin) {
      ""
    } else {
      jvmTargets.joinToString(";") { "jvm(\"$it\")" }
    }
    val kotlinBlock = if (kotlinPlugin.isEmpty()) "" else """
        kotlin{
        $jsBlock
        $jvmBlock
        }
    """.trimIndent()
    return File("build/functionalTest").gradleExec(
      buildGradleFile(kotlinPlugin, kotlinBlock),
      "tasks",
      "--all",
      "--stacktrace"
    )
  }

  val result = execute()

  // Verify the result
  jsTargets.forEach {
    val name = if (jsPlugin) "" else it
    result.output shouldContainIgnoringCase "assemble${name}KpmPublication"
    result.output shouldContainIgnoringCase "publish${name}KpmPublication"
  }
  jvmTargets.forEach {
    result.output shouldNotContainIgnoringCase "assemble${it}KpmPublication"
    result.output shouldNotContainIgnoringCase "publish${it}KpmPublication"
  }
  expectedMissingTasks.forEach {
    result.output shouldNotContainIgnoringCase it
  }
}

class KpmPublishPluginFunctionalTest : WordSpec(
  {
    "Applying Plugin" should {
      "Create tasks for Kotlin/multiplatform given [single JS target]" {
        taskCreationTest(
          "multiplatform",
          jsTargets = listOf("js")
        )
      }

      "Not create tasks for Kotlin/multiplatform given [single JVM target]" {
        taskCreationTest(
          "multiplatform",
          jvmTargets = listOf("jvm"),
          expectedMissingTasks = listOf(
            "assembleJsKpmPublication",
            "publishJsKpmPublication"
          )
        )
      }
      "Not create tasks for Kotlin/multiplatform given [multiple JS targets and single JVM target]" {
        taskCreationTest(
          "multiplatform",
          jsTargets = listOf("jsOne", "jsTwo"),
          jvmTargets = listOf("jvm"),
          expectedMissingTasks = listOf(
            "assembleJsKpmPublication",
            "publishJsKpmPublication"
          )
        )
      }
      "Create tasks for Kotlin/JS given [default JS target]" {
        taskCreationTest(
          "js",
          jsTargets = listOf("jsOne"),
          expectedMissingTasks = listOf(
            "assembleJsKpmPublication",
            "publishJsKpmPublication"
          )
        )
      }
      "Not create tasks for no kotlin plugin given [default JS target]" {
        taskCreationTest(
          "",
          expectedMissingTasks = listOf(
            "assembleJsKpmPublication",
            "assembleKpmPublication",
            "publishJsKpmPublication",
            "publishKpmPublication"
          )
        )
      }
    }

    "Running assembleKpmPublication" should {
      "succeed [JS]" {
        File("build/functionalTest").gradleExec(
          buildGradleFile(
            "js",
            """
      kotlin {
        js {browser()}
        dependencies {
          implementation(npm("axios", "*"))
          api(npm("snabbdom", "*"))
        }
      }
            """.trimIndent()
          ),
          "assembleKpmPublication",
          "--stacktrace"
        )
      }
      "succeed [MPP]" {
        File("build/functionalTest").gradleExec(
          buildGradleFile(
            "multiplatform",
            """
      kotlin {
        js {browser()}
        sourceSets {
          val jsMain by getting {            
            dependencies {
              implementation(npm("axios", "*"))
              api(npm("snabbdom", "*"))
            }
          }
        }
      }
            """.trimIndent()
          ),
          "assembleJsKpmPublication",
          "--stacktrace"
        )
      }
    }
    "Running publishKpmPublication [JS]" should {
      "succeed [JS]" {
        File("build/functionalTest").gradleExec(
          buildGradleFile(
            "js",
            """
      kotlin {
        js {browser()}
        dependencies {
          implementation(npm("axios", "*"))
          api(npm("snabbdom", "*"))
        }
      }
            """.trimIndent()
          ),
          "publishKpmPublication",
          "--stacktrace",
          "-Pkpm.publish.dry=true"
        )
      }
      "succeed [MPP]" {
        File("build/functionalTest").gradleExec(
          buildGradleFile(
            "multiplatform",
            """
      kotlin {
        js("CustomJS") {browser()}
        sourceSets {
          val CustomJSMain by getting {            
            dependencies {
              implementation(npm("axios", "*"))
              api(npm("snabbdom", "*"))
            }
          }
        }
      }
            """.trimIndent()
          ),
          "publishCustomJsKpmPublication",
          "--stacktrace",
          "-Pkpm.publish.dry=true"
        )
      }
    }
  }
)
