# Local settings
docs_dir: ${srcDir}
site_dir: ${outDir}
plugins:
  - search
#  - mike:
#      # these fields are all optional; the defaults are as below...
#      version_selector: true   # set to false to leave out the version selector
#      css_dir: css             # the directory to put the version selector's CSS
#      javascript_dir: js       # the directory to put the version selector's JS
#      canonical_version: null  # the version for <link rel="canonical">; `null`
#      # uses the version specified via `mike deploy`
# Site settings
site_name: npm-publish
site_author: Martynas Petuška
site_description: >-
  Gradle plugin enabling NPM publishing (essentially `maven-publish` for NPM packages). 
  Integrates seamlessly with Kotlin/JS/MPP plugin if applied, providing auto configurations.
site_url: https://mpetuska.github.io/npm-publish
repo_name: npm-publish
repo_url: https://github.com/mpetuska/npm-publish
remote_branch: gh-site
edit_uri: edit/master/npm-publish-docs/src/pages/
theme:
  name: material
  custom_dir: ${themeDir}
  features:
    - header.autohide
    - search.suggest
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
  logo: ./api/images/logo-icon.svg
  favicon: ./api/images/logo-icon.svg
  palette:
    - scheme: default
      primary: black
      accent: orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Turn off the light
    - scheme: slate
      primary: black
      accent: orange
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/lightbulb-outline
        name: Turn on the light
copyright: Copyright &copy; Martynas Petuška
extra:
  generator: false
  analytics:
    provider: google
    property: G-DVK22QBQZV
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://kotlinlang.slack.com/archives/C01LQTET9P1
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MartynasPetuska
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/petuska
    - icon: fontawesome/brands/github
      link: https://github.com/mpetuska
    - icon: fontawesome/solid/envelope
      link: mailto:martynas@petuska.dev
watch:
  - theme/
nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - User Guide:
      - User Guide: user-guide/index.md
      - Configuration:
          - Extension: user-guide/configuration/extension.md
  - API: api/
  - Changelog: CHANGELOG.md
