extra:
  generator: false
  analytics:
    provider: google
    property: G-DVK22QBQZV
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://kotlinlang.slack.com/archives/C01LQTET9P1
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MartynasPetuska
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/petuska
    - icon: fontawesome/brands/github
      link: https://github.com/mpetuska
    - icon: fontawesome/solid/envelope
      link: mailto:martynas@petuska.dev
