nav:
  - Home: index.md
  - User Guide:
      - User Guide: user-guide/index.md
      - Quick Start: user-guide/quick-start.md
      - Configuration:
          - Configuration: user-guide/configuration/index.md
          - Extension: user-guide/configuration/extension.md
          - Package: user-guide/configuration/package.md
          - Registry: user-guide/configuration/registry.md
          - Properties: user-guide/configuration/properties.md
      - Tasks:
          - Tasks: user-guide/tasks/index.md
          - NodeExecTask: user-guide/tasks/NodeExecTask.md
          - NpmExecTask: user-guide/tasks/NpmExecTask.md
          - NpmAssembleTask: user-guide/tasks/NpmAssembleTask.md
          - NpmPackTask: user-guide/tasks/NpmPackTask.md
          - NpmPublishTask: user-guide/tasks/NpmPublishTask.md
  - API: api/index.html
  - Changelog: CHANGELOG.md
  - License: LICENSE.md
