[versions]
detekt = "1.23.6"
dokka = "1.9.20"
java = "11"
junit-jupiter = "5.10.2"
kotest = "5.9.1"
kotlin = "2.0.0"

[libraries]
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json", version.ref = "kotest" }
plugin-container-tasks = "dev.petuska:container-tasks-gradle-plugin:0.0.4"
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-git-hooks = "com.github.jakemarsden:git-hooks-gradle-plugin:0.0.2"
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-node-gradle = "com.github.node-gradle:gradle-node-plugin:7.0.2"
plugin-versions = "com.github.ben-manes:gradle-versions-plugin:0.47.0"
plugin-versions-update = "nl.littlerobots.vcu:plugin:0.8.1"

[bundles]
kotest-assertions = [
  "kotest-assertions-core",
  "kotest-assertions-json",
]

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-publish = "io.github.gradle-nexus.publish-plugin:2.0.0"
plugin-publish = "com.gradle.plugin-publish:1.2.1"
