title: npm-publish
description: >-
  Gradle plugin enabling NPM publishing (essentially `maven-publish` for NPM packages). 
  Integrates seamlessly with Kotlin/JS/MPP plugin if applied, providing auto configurations.
show_downloads: false
google_analytics: G-DVK22QBQZV
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  #  - jekyll-feed
  - jekyll-toc
  - jekyll-menus

repository: mpetuska/npm-publish
output: web
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
url: https://npm-publish.petuska.dev
baseurl: "" # the subpath of your site, e.g. /blog
email: martynas@petuska.dev
author: Martynas Petuška
twitter_username: MartynasPetuska
github_username: mpetuska

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: "gen/api/**"
    values:
      layout: post
      author: Dokka
include:
  - "**/*.liquid"
exclude:
#  - "gen/"
---

# GH strict overrides
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
