source "https://rubygems.org"

group :jekyll_plugins do
    gem "github-pages"
    gem "jekyll-theme-hacker", "~> 0.2.0"
    gem "jekyll-redirect-from"
    gem "jekyll-coffeescript", "~> 1.1"
    gem "jekyll-default-layout", "~> 0.1.4"
    gem "jekyll-gist", "~> 1.5"
    gem "jekyll-github-metadata"
    gem "jekyll-optional-front-matter"
    gem "jekyll-paginate", "~> 1.1"
    gem "jekyll-readme-index", "~> 0.3.0"
    gem "jekyll-titles-from-headings", "~> 0.5.3"
    gem "jekyll-relative-links", "~> 0.6.1"
    gem "jekyll-toc", "~> 0.17.1"
    gem "jekyll-menus", "~> 0.6.1"
end

gem "webrick", "~> 1.7"

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
