site_name: npm-publish
site_author: Martynas Petuška
site_description: >-
  Gradle plugin enabling NPM publishing (essentially `maven-publish` for NPM packages). 
  Integrates seamlessly with Kotlin/JS/MPP plugin if applied, providing auto configurations.
site_url: https://mpetuska.github.io/npm-publish
repo_name: npm-publish
repo_url: https://github.com/mpetuska/npm-publish
remote_branch: gh-pages
edit_uri: edit/master/npm-publish-docs/src/doc/docs/
copyright: Copyright &copy; Martynas Petuška

# Meterial theme
#theme:
#  name: 'material'
#  palette:
#    - media: "(prefers-color-scheme: light)"
#      scheme: default
#      toggle:
#        icon: material/toggle-switch-off-outline
#        name: Switch to dark mode
#    - media: "(prefers-color-scheme: dark)"
#      scheme: slate
#      toggle:
#        icon: material/toggle-switch
#        name: Switch to light mode
#  features:
#    #- navigation.tabs
#    #- navigation.tabs.sticky
#    #- navigation.instant
#    - navigation.tracking
#    - navigation.top
theme:
  name: material
#  custom_dir: ${themeDir}
  features:
    - header.autohide
    - search.suggest
    - search.share
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
  logo: ./api/images/logo-icon.svg
  favicon: ./api/images/logo-icon.svg
  palette:
    - scheme: default
      primary: black
      accent: orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Turn off the light
    - scheme: slate
      primary: black
      accent: orange
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/lightbulb-outline
        name: Turn on the light
watch:
  - theme/

#plugins:
#  - search
#    Required for variables support (https://github.com/rosscdh/mkdocs-markdownextradata-plugin)
#  - markdownextradata
plugins:
  - search
  - markdownextradata

extra:
  generator: false
  analytics:
    provider: google
    property: GTM-TWJ9KQW
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://kotlinlang.slack.com/channels/npm-publish
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MartynasPetuska
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/petuska
    - icon: fontawesome/brands/github
      link: https://github.com/mpetuska
    - icon: fontawesome/solid/envelope
      link: mailto:martynas@petuska.dev

# Google Analytics
#  analytics:
#    provider: google
#    property: UA-XXXXXXXX-X

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
#
#markdown_extensions:
#  # Python Markdown
#  - abbr
#  - admonition
#  - attr_list
#  - def_list
#  - footnotes
#  - meta
#  - md_in_html
#  - toc:
#      permalink: true
#
#  # Python Markdown Extensions
#  - pymdownx.arithmatex:
#      generic: true
#  - pymdownx.betterem:
#      smart_enable: all
#  - pymdownx.caret
#  - pymdownx.details
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
#  - pymdownx.highlight
#  - pymdownx.inlinehilite
#  - pymdownx.keys
#  - pymdownx.mark
#  - pymdownx.smartsymbols
#  - pymdownx.superfences
#  - pymdownx.tabbed:
#      alternate_style: true
#  - pymdownx.tasklist:
#      custom_checkbox: true
#  - pymdownx.tilde

nav:
  - Home: index.md
  - User Guide:
      - User Guide: user-guide/index.md
      - Quick Start: user-guide/quick-start.md
      - Configuration:
          - Configuration: user-guide/configuration/index.md
          - Extension: user-guide/configuration/extension.md
          - Package: user-guide/configuration/package.md
          - Registry: user-guide/configuration/registry.md
          - Properties: user-guide/configuration/properties.md
      - Tasks:
          - Tasks: user-guide/tasks/index.md
          - NodeExecTask: user-guide/tasks/NodeExecTask.md
          - NpmExecTask: user-guide/tasks/NpmExecTask.md
          - NpmAssembleTask: user-guide/tasks/NpmAssembleTask.md
          - NpmPackTask: user-guide/tasks/NpmPackTask.md
          - NpmPublishTask: user-guide/tasks/NpmPublishTask.md
  - API: api/index.html
  - Changelog: CHANGELOG.md
  - License: LICENSE.md
