/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lt.petuska.kpm.publish

import io.kotest.core.spec.style.*
import io.kotest.matchers.*
import lt.petuska.kpm.publish.dsl.KpmPublishExtension.Companion.EXTENSION_NAME
import org.gradle.testfixtures.*

class KpmPublishPluginTest : WordSpec({
  "Using the Plugin ID" should {
    "Apply the Plugin" {
      val project = ProjectBuilder.builder().build()
      project.pluginManager.apply("lt.petuska.kpm.publish")
      
      project.plugins.getPlugin(KpmPublishPlugin::class.java) shouldNotBe null
    }
  }
  
  "Applying the Plugin" should {
    "Register the '$EXTENSION_NAME' extension" {
      val project = ProjectBuilder.builder().build()
      project.pluginManager.apply(KpmPublishPlugin::class.java)
      
      project.kpmPublish() shouldNotBe null
    }
  }
})
